[package]
name = "color_scheme"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus-std = { workspace = true, features = ["color_scheme"] }
dioxus = "0.4"
dioxus-web = "0.4"

log = "0.4.6"

# WebAssembly Debug
wasm-logger = "0.2.0"
console_error_panic_hook = "0.1.7"
