[workspace]
resolver = "2"
members = ["sdk", "examples/*"]
# We exclude the storage example from the workspace so that the dioxus features for other renderers are not enabled
exclude = ["examples/storage"]


[workspace.dependencies]
dioxus-sdk = { path = "./sdk" }
dioxus = { version = "0.5" }
dioxus-desktop = { version = "0.5" }
