[workspace]
resolver = "2"
members = ["sdk", "examples/*"]
#members = ["sdk"]


[workspace.dependencies]
dioxus-sdk = { path = "./sdk" }
dioxus = { version = "0.5" }
dioxus-web = { version = "0.5" }
dioxus-desktop = { version = "0.5" }
