[package]
name = "dioxus-std"
version = "0.1.0"
edition = "2021"


[features]
clipboard = ["dep:clipboard"]
notifications = ["dep:notify-rust"]
camera = ["dep:nokhwa"]

[dependencies]
#dioxus = "0.2"
clipboard = { version = "0.5.0", optional = true }
nokhwa = { version = "0.9.4", features = ["input-v4l", "input-msmf", "input-avfoundation", "input-jscam"], optional = true }
notify-rust = { version = "4.5.10", optional = true }

