[workspace]
resolver = "2"
members = [
    "std",
    "examples/*",
]

[workspace.dependencies]
dioxus-std = { path = "./std" }
dioxus = "0.5.0-alpha.0"
dioxus-web = "0.5.0-alpha.0"
dioxus-desktop = "0.5.0-alpha.0"