[package]
name = "dioxus-std"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#dioxus-core = "0.2.1"
clipboard = "0.5.0"
notify-rust = "4.5.10"

