[workspace]
resolver = "2"
members = [
    "std",
    "examples/*",
]

[workspace.dependencies]
dioxus-std = { path = "./std" }
dioxus = { version = "0.5.0-alpha.2" }
dioxus-web = { version = "0.5.0-alpha.2" }
dioxus-desktop = { version = "0.5.0-alpha.2" }