[package]
name = "dioxus-std"
version = "0.1.0"
authors = ["Jonathan Kelley", "Dioxus Labs", "ealmloff", "DogeDark"]
edition = "2021"
description = "Platform agnostic library for supercharging your productivity with Dioxus"
license = "MIT"
repository = "https://github.com/DioxusLabs/dioxus-std/"
homepage = "https://dioxuslabs.com"
keywords = ["dom", "gui", "dioxus", "standard", "hooks"]
categories = ["multimedia","os", "wasm"]

[workspace]
members = ["./examples/*"]

[features]
# Features
clipboard = ["dep:clipboard"]
notifications = ["dep:notify-rust"]
geolocation = ["dep:dioxus", "dep:windows", "dep:futures-lite"]

use_preferred_color_scheme = ["dep:dioxus", "dep:web-sys", "dep:wasm-bindgen"]
use_rw = ["dep:dioxus"]

default = ["use_preferred_color_scheme"]


[dependencies]
dioxus = { version = "0.3", optional = true }
web-sys = { version = "0.3.60", features = ["Window", "MediaQueryList"], optional = true }
wasm-bindgen = { version = "0.2.83", optional = true }

clipboard = { version = "0.5.0", optional = true }
windows = { version = "0.48.0", features = ["Foundation", "Devices_Geolocation"], optional = true }
notify-rust = { version = "4.8.0", optional = true }
cfg-if = "1.0.0"
futures-lite = {version = "1.13.0", optional = true }

[package.metadata.docs.rs]
all-features = true

