[package]
name = "storage-desktop"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus-sdk = { path = "../../sdk", features = ["storage"] }
dioxus = { version = "0.5", features = ["router"] }

[features]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
fullstack = ["dioxus/fullstack"]
server = ["dioxus/axum"]
