[package]
name = "geolocation"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus-std = { workspace = true, features = ["geolocation"] }
dioxus = { workspace = true }
dioxus-desktop ={ workspace = true }
# dioxus-web ={ workspace = true }
