[package]
name = "geolocation"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus-std = { workspace = true, features = ["geolocation"] }
# You can change from 'desktop' to 'web' as well
dioxus = { workspace = true, features = ["desktop"] } 
